version: '3'

services:
  webapi:
    image: klyushinmisha/home_io_backend
    build:
      context: .
      args:
        - CONFIG=config.py
        - REQUIREMENTS=requirements.dev.txt
      dockerfile: ci/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - avatars:/opt/home_io_backend/avarars

volumes:
  avatars:
    driver: local