version: '3'

services:
  webapi:
    image: klyushinmisha/home_io_backend
    container_name: home_io_backend_webapi
    build:
      context: .
      args:
        - CONFIG=config.py
        - REQUIREMENTS=requirements.txt
      dockerfile: ci/Dockerfile
    ports:
      - 8000:8000
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - MIGRATIONS_DIR=/opt/home_io_backend/home_io_backend/migrations
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:postgres@home_io_backend_postgres/home_io_backend
      - REDIS_BROKER_URI=redis://home_io_backend_redis:6379/0
      - REDIS_BACKEND_URI=redis://home_io_backend_redis:6379/1
      - SCRIPTS_PATH=/opt/home_io_backend/scripts_path
      - BUILDS_POOL=/opt/home_io_backend/builds_pool
      - HOME_IO_SDK_PATH=/opt/home_io_backend/build_utils/home_io_sdk
      - DOCKERFILE_PATH=/opt/home_io_backend/build_utils/Dockerfile
      - DOCKER_MACHINE_URI=${DOCKER_MACHINE_URI}
      - BACKEND_API_URL=${BACKEND_API_URL}
    volumes:
      - avatars:/opt/home_io_backend/avarars
      - scripts_path:/opt/home_io_backend/scripts_path
      - builds_pool:/opt/home_io_backend/builds_pool
    depends_on:
      - postgres
    restart:
      always

  postgres:
    image: postgres:11
    container_name: home_io_backend_postgres
    restart:
      on-failure
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5
    container_name: home_io_backend_redis
    restart:
      on-failure

volumes:
  avatars:
    driver: local
  scripts_path:
    driver: local
  builds_pool:
    driver: local
  postgres:
    driver: local