version: '3'

services:
  webapi:
    build:
      args:
        - REQUIREMENTS=requirements.dev.txt
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=env.py
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
      - FLASK_ENV=development
    command:
      flask run
    volumes:
      - ./home_io_backend:/opt/home_io_backend/home_io_backend

volumes:
  avatars:
    driver: local