version: '3'

services:
  webapi:
    image: klyushinmisha/home_io_backend
    build:
      context: .
      args:
        - CONFIG=config.py
        - REQUIREMENTS=requirements.dev.txt
      dockerfile: ci/Dockerfile
    ports:
      - 8000:8000
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - MIGRATIONS_DIR=/opt/home_io_backend/home_io_backend/migrations
    volumes:
      - avatars:/opt/home_io_backend/avarars
    depends_on:
      - postgres
    restart:
      always

  postgres:
    image: postgres:11
    restart:
      on-failure

volumes:
  avatars:
    driver: local