version: '3'

services:
  webapi:
    build:
      args:
        - CONFIG=test_config.py
        - REQUIREMENTS=requirements.test.txt
    command:
      python3 example.py --host=0.0.0.0 --port=8000

volumes:
  avatars:
    driver: local