version: '3'

services:
  api:
    build:
      context: .
      args:
        - CONFIG=config.py
        - REQUIREMENTS=requirements.dev.txt
    ports:
      - 8000:8000
    volumes:
      - avatars:/opt/home_io_backend/avarars

volumes:
  avatars:
    driver: local