"""fix constraint issue

Revision ID: 5539359db16b
Revises: db6a841c4ac2
Create Date: 2019-10-09 19:27:02.922711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5539359db16b'
down_revision = 'db6a841c4ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'device', ['id'])
    op.create_unique_constraint(None, 'device_log', ['id'])
    op.create_unique_constraint(None, 'device_task', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_task', type_='unique')
    op.drop_constraint(None, 'device_log', type_='unique')
    op.drop_constraint(None, 'device', type_='unique')
    # ### end Alembic commands ###
